# Generated by Django 4.2.4 on 2023-09-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_rename_aaddress_enquiry_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='confirmpassword',
            field=models.CharField(default=4, max_length=30),
            preserve_default=False,
        ),
    ]
