# Generated by Django 4.2.23 on 2025-09-28 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_table',
            fields=[
                ('Admin_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Admin_Name', models.CharField(max_length=100)),
                ('Admin_Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.PositiveBigIntegerField(default=0)),
                ('students_logged_in', models.PositiveBigIntegerField(default=0)),
                ('unique_active_students', models.PositiveBigIntegerField(default=0)),
                ('total_logins', models.PositiveBigIntegerField(default=0)),
                ('material_views', models.PositiveBigIntegerField(default=0)),
                ('material_downloads', models.PositiveBigIntegerField(default=0)),
                ('questions_posted', models.PositiveBigIntegerField(default=0)),
                ('answers_posted', models.PositiveBigIntegerField(default=0)),
                ('feedback_submitted', models.PositiveBigIntegerField(default=0)),
                ('complaints_submitted', models.PositiveBigIntegerField(default=0)),
                ('materials_uploaded', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='materials/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'mp4', 'mp3', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])])),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/%Y/%m/%d/')),
                ('preview_text', models.TextField(blank=True)),
                ('is_previewable', models.BooleanField(default=False)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('version_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('requires_enrollment', models.BooleanField(default=True)),
                ('download_count', models.PositiveBigIntegerField(default=0)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('newstext', models.TextField()),
                ('newsdate', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'adminapp_news',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('material_view', 'Material View'), ('material_download', 'Material Download'), ('question_post', 'Question Post'), ('answer_post', 'Answer Post'), ('feedback_submit', 'Feedback Submit'), ('complaint_submit', 'Complaint Submit')], max_length=50)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.program')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.year')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveBigIntegerField(default=0)),
                ('active_students_today', models.PositiveBigIntegerField(default=0)),
                ('materials_count', models.PositiveBigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('newstext', models.TextField()),
                ('newsdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('admins', 'Admins Only'), ('specific_program', 'Specific Program'), ('specific_branch', 'Specific Branch'), ('specific_year', 'Specific Year')], default='all', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_attachments/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.newscategory')),
                ('target_branches', models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.branch')),
                ('target_programs', models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.program')),
                ('target_years', models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.year')),
            ],
            options={
                'ordering': ['-is_pinned', '-priority', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('preview', 'Preview')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='adminapp.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.materialcategory'),
        ),
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='parent_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='adminapp.material'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.year'),
        ),
        migrations.CreateModel(
            name='BranchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveBigIntegerField(default=0)),
                ('active_students_today', models.PositiveBigIntegerField(default=0)),
                ('materials_count', models.PositiveBigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('course', 'title', 'version')},
        ),
    ]
