# Generated by Django 4.2.23 on 2025-09-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('active_students_today', models.PositiveIntegerField(default=0)),
                ('materials_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('students_logged_in', models.PositiveIntegerField(default=0)),
                ('unique_active_students', models.PositiveIntegerField(default=0)),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('material_views', models.PositiveIntegerField(default=0)),
                ('material_downloads', models.PositiveIntegerField(default=0)),
                ('questions_posted', models.PositiveIntegerField(default=0)),
                ('answers_posted', models.PositiveIntegerField(default=0)),
                ('feedback_submitted', models.PositiveIntegerField(default=0)),
                ('complaints_submitted', models.PositiveIntegerField(default=0)),
                ('materials_uploaded', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('active_students_today', models.PositiveIntegerField(default=0)),
                ('materials_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('material_view', 'Material View'), ('material_download', 'Material Download'), ('question_post', 'Question Post'), ('answer_post', 'Answer Post'), ('feedback_submit', 'Feedback Submit'), ('complaint_submit', 'Complaint Submit')], max_length=50)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
    ]
