# Generated by Django 4.2.23 on 2025-09-13 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_branchstats_dailystats_programstats_studentactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelTable(
            name='news',
            table='adminapp_news',
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('newstext', models.TextField()),
                ('newsdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('admins', 'Admins Only'), ('specific_program', 'Specific Program'), ('specific_branch', 'Specific Branch'), ('specific_year', 'Specific Year')], default='all', max_length=20)),
                ('target_programs', models.TextField(blank=True, help_text='Comma-separated program names')),
                ('target_branches', models.TextField(blank=True, help_text='Comma-separated branch names')),
                ('target_years', models.TextField(blank=True, help_text='Comma-separated year names')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='news_attachments/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.newscategory')),
            ],
            options={
                'ordering': ['-is_pinned', '-priority', '-publish_date'],
            },
        ),
    ]
