# Generated by Django 5.0.4 on 2024-04-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_table',
            fields=[
                ('Admin_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Admin_Name', models.CharField(max_length=100)),
                ('Admin_Password', models.CharField(max_length=20)),
            ],
        ),
    ]
