# Generated by Django 4.2.23 on 2025-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_complete_normalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsannouncement',
            name='target_branches',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='target_programs',
        ),
        migrations.RemoveField(
            model_name='newsannouncement',
            name='target_years',
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='target_branches',
            field=models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.branch'),
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='target_programs',
            field=models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.program'),
        ),
        migrations.AddField(
            model_name='newsannouncement',
            name='target_years',
            field=models.ManyToManyField(blank=True, related_name='targeted_news', to='adminapp.year'),
        ),
    ]
