# Generated by Django 4.2.23 on 2025-09-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('answered', models.CharField(max_length=50)),
                ('posteddate', models.CharField(max_length=30)),
                ('qid', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('postedby', models.CharField(max_length=50)),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StuResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=50)),
                ('responsetype', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('responsetext', models.TextField()),
                ('responsedate', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.program')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.year')),
            ],
        ),
    ]
