# Generated by Django 4.2.23 on 2025-09-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_newsannouncement_target_branches_and_more'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sturesponse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.branch'),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.program'),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='responsedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='responsetext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='responsetype',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='rollno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sturesponse',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.year'),
        ),
    ]
